project 'FocusNode+Example.xcodeproj'

platform :ios, '11.3'

target 'FocusNode+Example' do
  use_frameworks!

  pod 'FocusNode', path: '../'
  # pod 'SmartHitTest', path: '../../ARKit-SmartHitTest'
end
